[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_post = "A8LZ1pRNQe7cpLCUEdtE9WG1yARR1vmeyiLD4S4FsZq8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
